name: Java CI

on:
  push:
    branches: [ "main","CICD/kara"]
  pull_request:
    branches: [ "main","CICD/kara"]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Cache Maven packages
      uses: actions/cache@v4
      with:
        path: |
          ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Build with Maven
      run: mvn clean install -DskipTests

    - name: Start backend (in background)
      run: mvn spring-boot:run &

    - name: Wait for backend to start
      run: sleep 15

    - name: Download Apifox CLI
      run: |
        curl -fsSL https://cli.apifox.com/download/latest/linux_x64 -o apifox-cli
        chmod +x apifox-cli

    - name: Run API Fox tests
      run: ./apifox-cli run ./api-tests.json

    - name: Publish Test Report
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: target/surefire-reports/